### ISSUE TITLE
Question : APP_EMACS etc.

### ISSUE THREAD

**Issue by jasonm23** [algernon/ergodox-layout#86]
Hi @algernon how are you using the `APP` macros?  Looks like they're just typing the app name.

**Comment by algernon** [comment]
Yep, that's what they do. The real magic is in the `GUI` key: if I tap that twice, it sends `GUI+w` which triggers the [Switcher](https://extensions.gnome.org/extension/973/switcher/) GNOME Shell extension; then it switches to the APP layer.

Switcher displays a list of running applications, and if I type in their name, and hit `Enter`, it switches to it. This is where the APP layer keys come into play: they type the name in, hit enter, and toggle the layer off.

So the way I use them, is I hit `GUI+w 3` to switch to Emacs, for example.

**Comment by jasonm23** [comment]
Ok.  So any OS switcher could be activated and it would do the job.  I assumed it was something like this.

I use Os specific tools to hot key / speed dial my common apps, when it's possible.

**Comment by algernon** [comment]
Yes, exactly, any switcher would do the job. The reason I put this on the keyboard is because I wanted to have double-gui trigger the switcher app, and have the option there to either switch to a specific app with a single key, or type the name in myself. I either had to patch the switcher to add support for this, or patch the keyboard. I like C more than JavaScript, and I was knee-deep in the firmware anyway... :)
